# Generated by Django 6.0 on 2025-12-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighter',
            name='tag_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
